spring:
  #  데이터 베이스 관련 설정...
  datasource:
    url: jdbc:h2:tcp://localhost/~/data/spring-security
    username: sa
    password:
    driver-class-name: org.h2.Driver

  #  jpa 설정.
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

  thymeleaf:
    cache: false

# pass
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace